api:
  title: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'

  endpoints:
    signup: /api/auth/actions/signup

server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service-dev.default.svc.cluster.local:8088
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /$\{segment}
                - PreserveHostHeader
            - id: auth-service2
              uri: http://auth-service-dev.default.svc.cluster.local:8088
              predicates:
                - Path=/api/auth/**
              filters:
                - RewritePath=/api/auth/(?<segment>.*), /api/auth/$\{segment}
                - PreserveHostHeader

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.default.svc.cluster.local:8080/realms/ecc-realm

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: GATEWAY
        url: /v3/api-docs
      - name: AUTH SERVICE
        url: /auth/v3/api-docs
    urls-primary-name: AUTH SERVICE
