api:
  title: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'

  resources:
    jobs: /api/jobs

server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: job-api
              uri: http://job-service:8080
              predicates:
                - Path=/api/jobs/**
              filters:
              - PreserveHostHeader

            - id: job-service-docs
              uri: http://job-service:8080
              predicates:
                - Path=/jobs/v3/api-docs
              filters:
                - RewritePath=/jobs/v3/api-docs, /v3/api-docs

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/ecc-realm/protocol/openid-connect/certs
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://keycloak.local/realms/ecc-realm}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: Gateway API
        url: /v3/api-docs
      - name: Job API
        url: /jobs/v3/api-docs
    urls-primary-name: Gateway API
